<?php if(!$this->isStore()): ?>
    <div class="messages">
        <div class="message message-notice notice">
            <div><?php echo __('Please select store first!!') ?></div>
        </div>
    </div>
<?php elseif(!$this->validateApiKey()): ?>
    <div>
        <div class="messages">
            <div id="<?php /* @escapeNotVerified */ echo $block->getSuffixId('submit_key_messages')?>" style="display: none;"></div>
            <div class="message message-notice notice">
                <div><?php echo __('If you are already registered and have received our key, please type it below:') ?></div>
            </div>
        </div>
        <form id="<?php /* @escapeNotVerified */ echo $block->getSuffixId('submit_key_form')?>" action="<?php echo $block->apiKeyPostUrl() ?>" method="post">
            <fieldset class="fieldset admin__fieldset">
                <div class="admin__field field">
                    <label class="label admin__field-label">
                        <span><?php echo __("Api Key") ?></span>
                    </label>
                    <div class="admin__field-control control">
                        <input type="text" data-validate="{required:true}" id="<?php /* @escapeNotVerified */ echo $block->getSuffixId('submit_key_input')?>" class="admin__control-text" name="api_key" value="<?php echo $this->getApiKey() ?>"/>
                        <input name="form_key" type="hidden" value="<?php /* @escapeNotVerified */ echo $block->getFormKey() ?>" />
                    </div>
                    <button type="submit" title="Submit" class="action submit primary">
                        <span>Submit</span>
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
<?php endif; ?>
<iframe src="<?php echo $this->getIframeUrl();?>" style="width: 100%; min-height: 450px; border: none;" id="tracking"></iframe>
